ERROR:root:Failed to run command:LOG:'LogCommand' object has no attribute 'args'
Traceback (most recent call last):
  File "autobackup.py", line 36, in run
    self.data.update(command.run(self.data))
  File "autobackup.py", line 90, in run
    if len(self.args)<2:
AttributeError: 'LogCommand' object has no attribute 'args'
DEBUG:root:2018-10-21 14:35:40.512232
ERROR:root:Failed to run command:LOG:'NoneType' object is not iterable
Traceback (most recent call last):
  File "autobackup.py", line 37, in run
    self.data.update(command.run(self.data))
TypeError: 'NoneType' object is not iterable
DEBUG:root:2018-10-21 14:36:14.270444
